#spring:
#  #dubbo的配置文件
#  dubbo:
#    #dubbo中的服务名称
#    application: user-web
#    #dubbo的通讯协议名称
#    protocol:
#      name: dubbo
#    #zookeeper的注册中心地址
#    registry:
#      address: 192.168.1.103:2181
#      #zookeeper的通讯协议名称
#      protocol: zookeeper
#      #dubbo的服务面路径
#    base-package: com.guilin.gmall
#     consumer:
#       #设置超时时间
#       timeout: 600000
#       #检查服务是否存在
#       check: false





#server:
#  port: 8080
